# A Travis CI configuration file.

language: go

matrix:
    include:
        - os: linux
          sudo: required
          go: 1.7
          services: docker

git:
  depth: 3

before_install:
  - pip install --upgrade pip setuptools
  - ./tools/travis/setup.sh

install:
  - export DEPLOY_BUILD_READY=false
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/stretchr/testify
  - go get -u github.com/spf13/viper

script:
  - ./tools/travis/build.sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR;
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      ./tools/travis/test_openwhisk.sh;
    fi